# Generated by Django 5.0.7 on 2024-07-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_film_id_historyfilm_film_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
