# Generated by Django 5.0.7 on 2024-07-24 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films_serials', '0001_initial'),
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historyfilm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historyserial',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_serials.searchserial'),
        ),
        migrations.AddField(
            model_name='historyserial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
