# Generated by Django 5.0.7 on 2024-07-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyfilm',
            old_name='film_id',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='historyfilm',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historyserial',
            old_name='serial_id',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='historyserial',
            old_name='user_id',
            new_name='user',
        ),
    ]
