# Generated by Django 5.0.7 on 2024-08-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyfilm',
            options={'verbose_name': 'Историю поиска фильмов', 'verbose_name_plural': 'Истории поиска фильмов'},
        ),
        migrations.AlterModelOptions(
            name='historyserial',
            options={'verbose_name': 'Историю поиска сериалов', 'verbose_name_plural': 'Истории поиска сериалов'},
        ),
    ]
