# Generated by Django 5.0.7 on 2024-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('janr', models.CharField(max_length=60, null=True)),
                ('year', models.IntegerField(null=True)),
                ('country', models.CharField(null=True)),
                ('movie_length', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('age_rating', models.PositiveBigIntegerField(null=True)),
                ('picture', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('janr', models.CharField(max_length=60, null=True)),
                ('rating', models.FloatField(null=True)),
                ('release_year', models.CharField(max_length=60, null=True)),
                ('series_length', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(null=True)),
                ('age_rating', models.PositiveBigIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('picture', models.URLField(null=True)),
            ],
        ),
    ]
