# Generated by Django 5.0.7 on 2024-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfilm',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='searchserial',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
